#!/bin/bash

####################
#
#     Copyright 2011 Shannon Eric Peevey <speeves@erikin.com>
#
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#####################
#
# Sierra Trading Post Sight Search
# - Search and view Sierra Trading Post products view bash and ASCII art :P
# 
####################

HOMEDIR="/home/sad/serveradmindowntime"

### Initialize variables
STARTPAGEPIC="serveradmindowntime2.jpg"
TMP="/tmp/"
DRIVERSDIR="${HOMEDIR}/drivers/"
LOCALTMP="${HOMEDIR}/tmp/"
IMAGESDIR="${HOMEDIR}/images/"
JSAWKME="${HOMEDIR}/bin/jsawk"
WGETME="wget -qO - "
ITER=0
SLEEPTIME=5

# load our common library
. ${HOMEDIR}/common.sh

usage="
---------------------------
Usage: ${0} [-h]

 Help Options
 -h		This message

"
 
while getopts "hi:" OPT
do
    case $OPT in
	i )
	    I=$OPTARG
	    ;;
	h )
	    echo "$usage"
	    exit 1
	    ;;
	\?) 
	    echo "$usage"
            exit 1;;
	esac
done
# remove the flags from $@
shift $((${OPTIND} - 1))

startpage
